[package]
name = "macro-crate"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true


[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1.0.36"
proc-macro2 = "1.0.101"
mattro="0.1.2"